[format]
line-width = 80
indent-width = 2
indent-style = "space"
line-ending = "auto"
persistent-line-breaks = false
assignment-style = "arrow"
exclude = []
default-exclude = true
skip = []
table = []
default-table = true
