set.seed(1)
df <- data.frame(A = sample(LETTERS[1:3], 100, replace = TRUE), B = runif(100))
df$y <- (df$A == "A") + df$B + rnorm(100)
fit <- lm(y ~ A + B, df)

visreg(fit, "A", "B", top = "points", points = list(size = 2)) |> print() |> expect_silent()
visreg(fit, "A", "B", top = "line", points = list(size = 2)) |> print() |> expect_silent()
visreg(fit, "B", "A", top = "points", points = list(size = 2)) |> print() |> expect_silent()
visreg(fit, "B", "A", top = "line", points = list(size = 2)) |> print() |> expect_silent()
visreg(fit, "A", top = "points", points = list(size = 2)) |> print() |> expect_silent()
visreg(fit, "A", top = "line", points = list(size = 2)) |> print() |> expect_silent()
visreg(fit, "B", top = "points", points = list(size = 2)) |> print() |> expect_silent()
visreg(fit, "B", top = "line", points = list(size = 2)) |> print() |> expect_silent()

v <- visreg(fit, "B", plot = FALSE)
expect_equal(round(head(v$fit$visreg_fit), 3), c(0.033, 0.043, 0.054, 0.064, 0.075, 0.085))
