DF <- data.frame(A = sample(LETTERS[1:3], 100, replace = TRUE), B = runif(100))
DF$y <- (DF$A == "A") + DF$B + rnorm(100)
fit <- lm(y ~ A + B, DF)

visreg(fit, "A", "B", top = 'points', points = list(size = 2))
visreg(fit, "A", "B", top = 'line', points = list(size = 2))
visreg(fit, "B", "A", top = 'points', points = list(size = 2))
visreg(fit, "B", "A", top = 'line', points = list(size = 2))
visreg(fit, "A", top = 'points', points = list(size = 2))
visreg(fit, "A", top = 'line', points = list(size = 2))
visreg(fit, "B", top = 'points', points = list(size = 2))
visreg(fit, "B", top = 'line', points = list(size = 2))
